create table if not exists public.withdrawal_requests (
  withdrawal_request_id bigint generated by default as identity primary key,
  request_number varchar,
  group_id bigint references public.groups(group_id) on delete cascade,
  member_id bigint references public.members(member_id) on delete cascade,
  requested_amount numeric not null default 0,
  request_date date not null default current_date,
  reason varchar,
  status varchar not null default 'REQUESTED',
  approval_status varchar not null default 'PENDING',
  created_by bigint,
  creation_date timestamptz not null default now(),
  last_updated_by bigint,
  last_update_date timestamptz not null default now()
);

create index if not exists withdrawal_requests_group_idx
  on public.withdrawal_requests(group_id);

create index if not exists withdrawal_requests_member_idx
  on public.withdrawal_requests(member_id);

alter table public.withdrawal_requests enable row level security;

drop policy if exists withdrawal_requests_read on public.withdrawal_requests;
drop policy if exists withdrawal_requests_insert on public.withdrawal_requests;
drop policy if exists withdrawal_requests_update on public.withdrawal_requests;

create policy withdrawal_requests_read
  on public.withdrawal_requests
  for select
  using (true);

create policy withdrawal_requests_insert
  on public.withdrawal_requests
  for insert
  with check (true);

create policy withdrawal_requests_update
  on public.withdrawal_requests
  for update
  using (true)
  with check (true);
